### ISSUE TITLE
Question for the Generator

### ISSUE THREAD

**Issue by gerug-dev** [GlassBricks/HipsterRomGenerator#1]
@GlassBricks 
Hey, could you please explain how the Generator works?
I would love to use it.

Also i have another question and i hope i'm not asking for too much. 
I really love your resource pack you are using for redstone, pistons, note block etc.
Is there any chance you could make that available or give it to me please?

Thanks in advance.
You are doing really great tutorials.

**Comment by GlassBricks** [comment]
Hi! Thanks for the inquiry.

This project is a kotlin/gradle project with a bunch of random scripts located in `romGenerator/scripts`, abusing Kotest (a test framework) for that.
If you want to try it yourself, use the IDE Intellij Idea, install the Kotest plugin, clone this project, import gradle project, etc.. In the script files, run buttons should appear.
Note that I haven't bothered to  document this super well.

As for the texturepack, I'm using some some manually edited combination of [Downshift](https://www.planetminecraft.com/texture-pack/downshift-4873674/), [Redstone Reloaded](https://www.planetminecraft.com/texture-pack/redstone-reloaded/), and [vanilla tweaks](https://vanillatweaks.net/picker/resource-packs/), and [iRedstone modern](https://www.planetminecraft.com/texture-pack/iredstone/).
If you're gonna do just one texture pack, probably Downshift is the one you're looking for.

**Comment by gerug-dev** [comment]
Thanks for your answer.
The Kotest plugin was missing and now it works, thanks.

Also i really love the texturepacks, thanks for the links. :-)
I will close that issue as you answered everything :-)
